// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('zero.webappsecurityB', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('zero.webappsecurityB', async function() {
    /*await driver.get("http://zero.webappsecurity.com/")
    //await driver.setRect(1920, 1047)
    await driver.findElement(By.css("#onlineBankingMenu strong")).click()
    await driver.findElement(By.css(".row:nth-child(1) > .span12")).click()
    await driver.findElement(By.css("#feedback strong")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.css(".signin-controls")).click()
    await driver.findElement(By.id("subject")).click()
    await driver.findElement(By.css(".control-group:nth-child(1) > .controls")).click()
    await driver.findElement(By.css("p:nth-child(3)")).click()
    await driver.findElement(By.css(".top_offset > .row")).click()
    await driver.findElement(By.id("feedback-title")).click()
    await driver.findElement(By.css(".icon-signin")).click()
    await driver.findElement(By.id("user_login")).click()
    await driver.findElement(By.id("user_login")).sendKeys("username")
    await driver.findElement(By.id("user_password")).sendKeys("password")
    await driver.findElement(By.name("submit")).click()
    await driver.findElement(By.css(".top_offset > .row:nth-child(2) > .span12")).click()
    await driver.findElement(By.css(".board-header:nth-child(5)")).click()*/
	await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q')).sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  })
})


/*
// Load dependencies
var assert = require('chai').assert,
test = require('selenium-webdriver/testing'),
webdriver = require('selenium-webdriver');

// Our test
test.describe('Test', function () {
test.it('Title should be "The Internet"', function () {
// Set timeout to 10 seconds
this.timeout(10000);

// Get driver
// var driver = new webdriver.Builder().
// withCapabilities(webdriver.Capabilities.firefox()).
// build();
// var driver = new webdriver.Builder().
// withCapabilities(webdriver.Capabilities.edge()).
// build();
// var driver = new webdriver.Builder().
// withCapabilities(webdriver.Capabilities.ie()).
// build();
var driver = new webdriver.Builder().
withCapabilities(webdriver.Capabilities.chrome()).
build();

// Go to URL
driver.get('http://the-internet.herokuapp.com');

// Find title and assert
driver.executeScript('return document.title').then(function(return_value) {
assert.equal(return_value, 'The Internet')
});

// Quit webdriver
driver.quit();
});
});*/


/*const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('chrome').build();
  try {
    await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  } finally {
    await driver.quit();
  }
})();*/

/*
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('zero.webappsecurityA', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    //await driver.quit();
  })
  it('zero.webappsecurityA', async function() {
	await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  })
})*/


/*const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('chrome').build();
  try {
    await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  } finally {
	//await setTimeout(function () {driver.quit()}, 10000);  
    await driver.quit();
	
  }
})();*/


/*
var webdriver = require('selenium-webdriver');
var driver = new webdriver.Builder()
	.forBrowser('chrome')
	.build();
driver.get('http://www.google.com');

var element = driver.findElement(webdriver.By.name('q'));
element.sendKeys('Cheese!');
element.submit();

driver.getTitle().then(function(title) {
  console.log('Page title is: ' + title);
});

driver.wait(function() {
  return driver.getTitle().then(function(title) {
    return title.toLowerCase().lastIndexOf('cheese!', 0) === 0;
  });
}, 30000);

driver.getTitle().then(function(title) {
  console.log('Page title is: ' + title);
});

driver.quit();*/